name: generate-doc
run-name: Generate documentation

on: 
  push:
    branches:
      - "main"
    paths:
      - "webui.nim"
      - "nimdoc.cfg"
      - "webui.nimble"

      - "docs/**"
      - "webui/**"
      - ".github/workflows/**"

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: devel # for better docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate documentation
        run: nimble doc -d:useWebuiDll webui.nim

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: docs
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
